config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get '/send_message/:id', to: 'rooms#init_chat', as: :init_chat

  resources :posts, except: [:new] do
    post '/react', to: 'likes#action', as: :react
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show]
  resources :followings, only: [:index, :create, :destroy]
  resources :rooms, only: [:show, :index]
  resources :messages, only: [:create]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :text, length: { minimum: 4 }, presence: true

  def isliked?(user)
    !likes.where(user_id: user.id).empty?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = current_user.followings_and_own_posts
    @post = Post.new
    @comment = Comment.new
  end

  def create
    post = current_user.posts.build(post_params)

    if post.save
      redirect_to request.referrer, notice: 'post was created successfuly.'
    else
      redirect_to request.referrer, alert: 'post was not created please try again.'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(text: params[:post][:text])
      redirect_to root_path, notice: 'Your post was updated successfully.'
    else
      redirect_to request.referrer, alert: 'Your post couldn\'t be updated, please try again.'
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to request.referrer, notice: 'post deleted succesfully'
    else
      redirect_to request.referrer, alert: 'Post wasn\'t deleted cause of a server error'
    end
  end

  private

  def post_params
    params.require(:post).permit(:text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_heart(post)
    if post.isliked?(current_user)
      render 'empty_heart'
    else
      render 'filled_heart'
    end
  end

  def get_edit_and_remove_btns(post)
    return unless current_user == post.author

    render partial: 'edit_remove_btns', locals: { post: post }
  end

  def get_comment_trash(post, comment)
    return unless current_user == comment.user

    render partial: 'trash_btn', locals: { post: post, comment: comment }
  end
end

app/views/posts/_edit_remove_btns.html.erb
<%= link_to edit_post_path(post), class: 'px-3 text-base' do %>
  <i class="fas fa-edit"></i>
<% end %>
<%= link_to post_path(post), class: 'px-3 text-base', method: :delete, data: {confirm: "Are you sure?"} do %>
  <i class="fas fa-trash-alt"></i>
<% end %>

app/views/posts/_empty_heart.html.erb
<i class="fas fa-heart"></i>

app/views/posts/_filled_heart.html.erb
<i class="far fa-heart"></i>

app/views/posts/_side_bar.html.erb
<div class="sidbar-size-2 inside-vh scroll-y who-to-follow border-left">
  <div class="text-muted d-flex justify-content-between p-3 py-4">
    <div class="font-weight-bold text-uppercase">
      who to follow
    </div>
    <i class="fas fa-sync-alt"></i>
  </div>
  <hr class="mx-4 m-0" />
  <div class="people p-3">
    <% current_user.out_users.each do |person| %>
      <div class="person d-flex align-items-center p-2">
        <%= link_to user_path(person) do %>
          <% if person.avatar.attached? %>
            <%= image_tag person.avatar, class: 'person-image rounded-circle' %>
          <% end %>
        <% end %>
        <div class="pl-2 d-flex flex-column">
          <%= link_to user_path(person), class: 'text-decoration-none text-dark' do %>
            <span class="font-weight-bold"><%= person.fullname %></span>
          <% end %>
          <% unless person.followed_by.nil? %>
            <span class="text-muted">Followed by <span class="text-base"><%= person.followed_by[0].fullname %></span></span>
          <% else %>
            <span class="text-muted">Be the first follower</span>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="text-base small-font">
      <a href="#" class="text-base text-decoration-none">Popular accounts</a> -
      <a href="#" class="text-base text-decoration-none">Find Friends</a>
    </div>
  </div>
</div>

app/views/posts/_trash_btn.html.erb
<%= link_to post_comment_path(post, comment), class: 'text-decoration-none text-base', method: :delete do %>
  <i class="fas fa-trash-alt"></i>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col inside-vh scroll-y">
    <div class="mx-4 my-5">
      <div class="post-form py-3 px-4 mb-5 bg-white">
        <div class="p-2">
          <span class="font-weight-bold text-uppercase text-muted">you made a mistake? feel free to update :)</span>
        </div>
        <%= simple_form_for @post do |f| %>
          <div class="form-group w-100">
            <%= f.input_field :text, placeholder: 'Share to help your colleagues...', class: 'w-100 form-control' %>
          </div>
          <%= f.button :submit, 'save', class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'side_bar' %>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col inside-vh scroll-y">
    <div class="mx-4 my-5">
      <div class="post-form py-3 px-4 mb-5 bg-white">
        <div class="p-2">
          <span class="font-weight-bold text-uppercase text-muted">What's in your mind?</span>
        </div>
        <%= simple_form_for @post do |f| %>
          <div class="form-group w-100">
            <%= f.input_field :text, :as => :string, placeholder: 'Share to help your colleagues...', class: 'w-100 form-control' %>
          </div>
        <% end %>
      </div>
      <div class="post-container bg-white">
        <div class="text-uppercase font-weight-bold text-base px-4 py-3">
          new posts
        </div>
        <hr class="p-0 my-0 mx-4" />
        <div class="py-3 px-4">
          <% @posts.each do |post| %>
            <div id='post-<%= post.id %>' class="d-flex w-100 py-3">
              <%= render partial: 'user_image', locals: { user: post.author } %>
              <div class="post-info w-100 pl-2">
                <div class="d-flex w-100 justify-content-between">
                  <%= link_to user_path(post.author), class: 'text-decoration-none text-dark' do %>
                    <div class="text-capitalize font-weight-bold"><%= post.author.fullname %></div>
                  <% end %>
                  <div class="small-font text-muted"><%= time_ago_in_words(post.created_at) %></div>
                </div>
                <div class="text-muted">
                  <%= post.text %>
                </div>
                <div class="w-100 d-flex justify-content-end">
                  <%= link_to post_react_path(post), method: :post, class: 'px-3 text-base text-decoration-none' do %>
                    <span class="pr-2"><%= post.likes.count %></span>
                    <%= get_heart(post) %>
                  <% end %>
                  <%= get_edit_and_remove_btns(post) %>
                </div>
                <%= simple_form_for @comment, url: post_comments_path(post) do |f| %>
                  <div class="d-flex align-items-baseline w-100 py-3">
                    <%= render partial: 'user_image', locals: { user: current_user } %>
                    <div class="form-group w-100 px-3">
                      <%= f.input_field :text, :as => :string, placeholder: 'Leave a comment...', class: 'w-100 form-control' %>
                    </div>
                  </div>
                <% end %>
                <div class="w-100 comments-container">
                  <% post.comments.each do |comment| %>
                    <div class="comment-container w-100">
                      <div class="w-100 d-flex pt-3">
                        <%= render partial: 'user_image', locals: { user: comment.user } %>
                        <div class="w-100 pl-2">
                          <div class="font-weight-bold text-capitalize">
                            <%= link_to user_path(comment.user), class: 'text-dark text-decoration-none' do %>
                              <%= comment.user.fullname %>
                            <% end %>
                          </div>
                          <div class="text-muted">
                            <%= comment.text %>
                          </div>
                        </div>
                      </div>
                      <div class="d-flex justify-content-end pr-4">
                        <%= get_comment_trash(post, comment) %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'side_bar' %>
</div>