config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get '/send_message/:id', to: 'rooms#init_chat', as: :init_chat

  resources :posts, except: [:new] do
    post '/react', to: 'likes#action', as: :react
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show]
  resources :followings, only: [:index, :create, :destroy]
  resources :rooms, only: [:show, :index]
  resources :messages, only: [:create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_if_there_is_new_messages, only: %i[index show]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username fullname avatar cover_picture])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username fullname avatar cover_picture])
  end

  def check_if_there_is_new_messages(user = current_user)
    @unread_messages = 0

    if user
      rooms = user.rooms.uniq
      rooms.each do |room|
        @unread_messages += room.messages.where('unread = true and user_id != ?', user.id).count
      end
    end

    @unread_messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active text-white' if request.path == test_path

    ''
  end

  def add_user_image(user)
    if user.avatar.attached?
      render partial: 'avatar_user_image', locals: { user: user }
    else
      render 'avatar_user_fake_image'
    end
  end

  def add_rounded_user_image(user)
    if user.avatar.attached?
      render partial: 'rounded_user_image', locals: { user: user }
    else
      render partial: 'rounded_user_fake_image'
    end
  end

  def get_follower(person)
    if !person.followed_by.nil?
      render partial: 'followed_by', locals: { user: person }
    else
      render 'no_follower'
    end
  end

  def no_followers_message(followers)
    render 'no_followers' if followers.empty?
  end

  def get_user_follower(follower)
    if !follower.followed_by.nil?
      if follower.followed_by.follower == current_user
        render 'me_follower'
      else
        render partial: 'followed_by_2', locals: { follower: follower }
      end
    else
      render 'no_follower'
    end
  end

  def render_add_or_remove_btn(follower)
    return if follower == current_user

    if current_user.following?(follower)
      render partial: 'minus_btn', locals: { follower: follower }
    else
      render partial: 'plus_btn', locals: { follower: follower }
    end
  end

  def render_edit_or_follow_btn(user)
    if user == current_user
      render 'edit_btn'
    else
      render_add_or_remove_btn(user)
    end
  end

  def get_profile_image(user)
    if user.avatar.attached?
      render partial: 'profile_image', locals: { user: user }
    else
      render 'fake_profile_image'
    end
  end

  def get_message_btn(user)
    if current_user == user
      render 'hamburger'
    else
      render 'message_btn'
    end
  end

  def get_cover_image(user)
    if user.cover_picture.attached?
      render partial: 'cover_image', locals: { user: user }
    else
      render 'fake_cover_image'
    end
  end

  def render_side_bar
    render 'left_side_bar' if user_signed_in?
  end

  def render_top_bar
    if user_signed_in?
      render 'navbar_links'
    else
      render 'log_in_links'
    end
  end

  def hide_messages_notice(unread)
    unread.nil? || unread.zero? ? 'd-none' : ''
  end

  def get_alert_class(alert)
    'alert' if alert
  end

  def get_message(message)
    message
  end

  def render_notification(notice, alert)
    return unless notice || alert

    render partial: 'notification', locals: { notice: notice, alert: alert }
  end
end

app/views/application/_avatar_user_fake_image.html.erb
<%= image_tag 'https://addisonavenuemarketing.com/wp-content/uploads/2016/07/facebook-avatar.jpg', class: "user-image" %>

app/views/application/_avatar_user_image.html.erb
<%= image_tag user.avatar, class: "user-image" %>

app/views/application/_edit_btn.html.erb
<%= link_to edit_user_registration_path, class: 'text-decoration-none' do %>
  <div class="text-muted border-muted border rounded-circle d-flex justify-content-center align-items-center follow-button">
    <i class="fas fa-user-edit"></i>
  </div>
<% end %>

app/views/application/_followed_by.html.erb
<span class='text-muted'>Followed by <span class='text-base'><%= user.followed_by.follower.fullname %></span></span>

app/views/application/_log_in_links.html.erb
<%= link_to new_user_session_path, class: 'px-3 py-2 font-weight-bold text-darkblue text-decoration-none' do %>
  Log In
<% end %>
<%= link_to new_user_registration_path, class: 'px-3 py-2 font-weight-bold text-darkblue text-decoration-none' do %>
  Register
<% end %>

app/views/application/_minus_btn.html.erb
<%= link_to following_path(follower), method: :delete, class: 'text-decoration-none' do %>
  <div class="text-muted border-muted border rounded-circle d-flex justify-content-center align-items-center follow-button">
    <i class="fas fa-minus"></i>
  </div>
<% end %>

app/views/application/_no_follower.html.erb
<span class='text-muted'>Be the first follower</span>

app/views/application/_no_followers.html.erb
<div class="text-capitalize text-muted text-center">
  no one is following this guy, be the first one to follow him.
</div>

app/views/application/_plus_btn.html.erb
<%= link_to followings_path(followed_id: follower), method: :post, class: 'text-decoration-none' do %>
  <div class="text-muted border-muted border rounded-circle d-flex justify-content-center align-items-center follow-button">
    <i class="fas fa-plus"></i>
  </div>
<% end %>

app/views/application/_profile_image.html.erb
<%= image_tag user.avatar, class: 'profile-image rounded-circle m-3' %>

app/views/application/_rounded_user_fake_image.html.erb
<%= image_tag 'https://addisonavenuemarketing.com/wp-content/uploads/2016/07/facebook-avatar.jpg', class: 'person-image rounded-circle' %>

app/views/application/_user_image.html.erb
<%= link_to user_path(user) do %>
  <%= add_user_image(user) %>
<% end %>

app/views/application/_user_info.html.erb
<div class="sidbar-size-2 inside-vh scroll-y who-to-follow border-left">
  <div class="user-profile">
    <div class="d-flex justify-content-center align-items-center">
      <%= render_edit_or_follow_btn(user) %>
      <%= get_profile_image(user) %>
      <div class="text-muted border-muted border rounded-circle d-flex justify-content-center align-items-center follow-button">
        <%= get_message_btn(user) %>
      </div>
    </div>
    <div class="w-100 d-flex justify-content-center flex-column mb-3">
      <div class="text-uppercase text-center font-weight-bold">
        <%= user.fullname %>
      </div>
      <div class="text-muted text-center small-font">
        @<%= user.username %>
      </div>
    </div>
  </div>
  <div class="d-flex border-top border-bottom border-muted">
    <div class="d-flex justify-content-center align-items-center flex-column py-3 third-width">
      <div class="font-weight-bold">
        <%= user.posts.count %>
      </div>
      <div class="text-capitalize text-muted small-font">
        tweets
      </div>
    </div>
    <div class="d-flex justify-content-center align-items-center flex-column py-3 third-width border-right border-left border-muted">
      <div class="font-weight-bold">
        <%= user.followings.count %>
      </div>
      <div class="text-capitalize text-muted small-font">
        following
      </div>
    </div>
    <div class="d-flex justify-content-center align-items-center flex-column py-3 third-width">
      <div class="font-weight-bold">
        <%= user.followers.count %>
      </div>
      <div class="text-capitalize text-muted small-font">
        followers
      </div>
    </div>
  </div>
  <div class="text-muted d-flex justify-content-between p-3 py-4">
    <div class="font-weight-bold text-uppercase">
      followed by
    </div>
  </div>
  <hr class="m-0 mx-4" />
  <div class="people p-3">
    <%= no_followers_message(user.followers) %>
    <% user.followers.each do |follow| %>
      <div class="d-flex justify-content-between align-items-center">
        <div class="person d-flex align-items-center p-2">
          <%= render partial: 'user_rounded_image', locals: { user: follow.follower } %>
          <div class="pl-2 d-flex flex-column">
            <%= link_to user_path(follow.follower), class: 'text-decoration-none text-dark' do %>
              <span class="font-weight-bold"><%= follow.follower.fullname %></span>
            <% end %>
            <%= get_user_follower(follow.follower) %>
          </div>
        </div>
        <%= render_add_or_remove_btn(follow.follower) %>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_user_rounded_image.html.erb
<%= link_to user_path(user) do %>
  <%= add_rounded_user_image(user) %>
<% end %>